function skillMember() {
  const member = document.querySelectorAll('.member');
  const memberSkill = document.querySelectorAll('.member-skill');
  const memberSkillList = document.querySelectorAll('.member-skill-list');
  const memberSkillListLi = document.querySelectorAll('.member-skill-list li');
  const memberSkillListLiA = document.querySelectorAll('.member-skill-list li a');
  const memberSkillListLiSpan = document.querySelectorAll('.member-skill-list li span');
  const memberSkillListLiSpanI = document.querySelectorAll('.member-skill-list li span i');
  const memberSkillListLiSpanI2 = document.querySelectorAll('.member-skill-list li span i:nth-child(2)');
  const memberSkillListLiSpanI3 = document.querySelectorAll('.member-skill-list li span i:nth-child(3)');
  const memberSkillListLiSpanI4 = document.querySelectorAll('.member-skill-list li span i:nth-child(4)');
  const memberSkillListLiSpanI5 = document.querySelectorAll('.member-skill-list li span i:nth-child(5)');
  const memberSkillListLiSpanI6 = document.querySelectorAll('.member-skill-list li span i:nth-child(6)');
  const memberSkillListLiSpanI7 = document.querySelectorAll('.member-skill-list li span i:nth-child(7)');
  const memberSkillListLiSpanI8 = document.querySelectorAll('.member-skill-list li span i:nth-child(8)');
  const memberSkillListLiSpanI9 = document.querySelectorAll('.member-skill-list li span i:nth-child(9)');
  const memberSkillListLiSpanI10 = document.querySelectorAll('.member-skill-list li span i:nth-child(10)');
  const memberSkillListLiSpanI11 = document.querySelectorAll('.member-skill-list li span i:nth-child(11)');
  const memberSkillListLiSpanI12 = document.querySelectorAll('.member-skill-list li span i:nth-child(12)');
  const memberSkillListLiSpanI13 = document.querySelectorAll('.member-skill-list li span i:nth-child(13)');
  const memberSkillListLiSpanI14 = document.querySelectorAll('.member-skill-list li span i:nth-child(14)');
  const memberSkillListLiSpanI15 = document.querySelectorAll('.member-skill-list li span i:nth-child(15)');
  const memberSkillListLiSpanI16 = document.querySelectorAll('.member-skill-list li span i:nth-child(16)');
  const memberSkillListLiSpanI17 = document.querySelectorAll('.member-s
